#!/bin/sh

if command -v musl-gcc > /dev/null; then compiler=musl-gcc; else compiler=gcc; fi
compiler_options="-Wunused-label -Wunused-value -Wunused-variable -Wfatal-errors -std=c11 -O3 -static"
$compiler $compiler_options src/main.c -o exe/readline
chmod +x exe/readline
